"""Add is_popular to Artist

Revision ID: 01525eb36232
Revises: 3694954d3394
Create Date: 2025-08-09 10:51:12.315982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01525eb36232'
down_revision = '3694954d3394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_popular', sa.Boolean(), nullable=True))

    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('artist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist', sa.VARCHAR(length=255), nullable=True))

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('is_popular')

    # ### end Alembic commands ###
