"""Add artist_id to Song model

Revision ID: 3694954d3394
Revises: f77dd91cdba5
Create Date: 2025-08-09 10:34:58.458000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3694954d3394'
down_revision = 'f77dd91cdba5'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_song_artist_id_artist',  # <-- Yeh constraint ka naam hai, zaruri hai
            'artist',                    # Reference table
            ['artist_id'],               # Column in song table
            ['id']                      # Referenced column in artist table
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('artist_id')

    # ### end Alembic commands ###
