"""Add timestamp to recently_played

Revision ID: 6698faaeef85
Revises: 
Create Date: 2025-08-08 11:05:33.147647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6698faaeef85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('song_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('recently_played', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_column('played_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recently_played', schema=None) as batch_op:
        batch_op.add_column(sa.Column('played_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('song_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
