"""Add nullable position to QueueItem

Revision ID: 9871a122a013
Revises: b74c07de7f7f
Create Date: 2025-08-13 17:28:59.155258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9871a122a013'
down_revision = 'b74c07de7f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_item', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
