"""Add position column to QueueItem

Revision ID: b74c07de7f7f
Revises: 707680b69863
Create Date: 2025-08-13 17:26:33.592330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74c07de7f7f'
down_revision = '707680b69863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_item', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
